/**
 * This file is auto-generated by scripts/generate-class.mjs.
 * Do not edit manually - re-run `npm run generate:client` to update.
 */
export * from './generated';
export { SupabaseManagementAPI } from './api';
export type { SupabaseManagementAPIOptions } from './api';
export { SupabaseManagementAPIError } from './error';
export { SUPABASE_API_BASE_URL } from './consts';
