/**
 * This file is auto-generated by scripts/generate-class.mjs.
 * Do not edit manually - re-run `npm run generate:client` to update.
 */
export * from './generated';
export { SupabaseManagementAPI } from './api';
